<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <OutputType Condition="'$(Configuration)' == 'Release'">WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Version>0.6.2</Version>
    <Company>ZenQuant</Company>
    <Product>NullWave</Product>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/Art/**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="tests/**" />
    <InternalsVisibleTo Include="NullWave.Tests" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="CHANGELOG.md" />
  </ItemGroup>
  <!-- NuGet packages -->
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="LibVLCSharp" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Filters.Expressions" />
    <PackageReference Include="sqlite-net-pcl" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" />
    <PackageReference Include="TagLibSharp" />
    <PackageReference Include="Velopack" />
  </ItemGroup>
</Project>